### ISSUE TITLE
Compatibility with PHP 7.1

### ISSUE THREAD

**Issue by mprofitl** [twiro/reflecteduploadfield#12]
Hello twiro

The hoster of a client informs me that PHP 5.6 will not receive updates after 2018. I am trying to switch to the current PHP version 7.1 but I get an error message.

Are you planning to update this extension? I am using it in all of my projects by the way to give files proper and search engine friendly names.

**Comment by twiro** [comment]
Hey Moritz,

you just reminded my that I updated this extension a few months ago and didn't publish my changes til now – so here is **[version 1.3.0](https://github.com/twiro/reflecteduploadfield/releases/tag/1.3.0)** :)

Should be fully compatible with Symphony 2.7.X and PHP 7.X – at least I didn't run into any troubles in the 3 or 4 projects that I already use this latest version with!

> _Are you planning to update this extension? I am using it in all of my projects by the way to give files proper and search engine friendly names._

Great to hear it's that useful for you! I'm using it for the same purpose in nearly all of my projects, so I hope my support for this extension won't end anytime soon ;) And if you like the extension watching/staring the repo is always welcome :) _(gives the repo a little more 'reputation')_

PS: Glückwunsch zur Selbstständigkeit übrigens 👍  Ist das eher als temporäre Auszeit oder doch als langfristige Lösung gedacht? Und arbeitest du dann auch beruflich mit Symphony momentan?
